export const BUY_CREDIT_START = 'BUY_CREDIT_START';
export const BUY_CREDIT_SAGA = 'BUY_CREDIT_SAGA';
export const BUY_CREDIT_SUCCESS = 'BUY_CREDIT_SUCCESS';
export const BUY_CREDIT_FAIL = 'BUY_CREDIT_FAIL';

export const APPLY_GRADING_START = 'APPLY_GRADING_START';
export const APPLY_GRADING_SAGA = 'APPLY_GRADING_SAGA';
export const APPLY_GRADING_SUCCESS = 'APPLY_GRADING_SUCCESS';
export const APPLY_GRADING_FAIL = 'APPLY_GRADING_FAIL';

export const BUY_COLLECTION_START = 'BUY_COLLECTION_START';
export const BUY_COLLECTION_SAGA = 'BUY_COLLECTION_SAGA';
export const BUY_COLLECTION_SUCCESS = 'BUY_COLLECTION_SUCCESS';
export const BUY_COLLECTION_FAIL = 'BUY_COLLECTION_FAIL';

export const VALIDATE_PAYMENT_START = 'VALIDATE_PAYMENT_START';
export const VALIDATE_PAYMENT_SAGA = 'VALIDATE_PAYMENT_SAGA';
export const VALIDATE_PAYMENT_SUCCESS = 'VALIDATE_PAYMENT_SUCCESS';
export const VALIDATE_PAYMENT_FAIL = 'VALIDATE_PAYMENT_FAIL';

export const PAYMENT_HISTORY_START = 'PAYMENT_HISTORY_START';
export const PAYMENT_HISTORY_SAGA = 'PAYMENT_HISTORY_SAGA';
export const PAYMENT_HISTORY_SUCCESS = 'PAYMENT_HISTORY_SUCCESS';
export const PAYMENT_HISTORY_FAIL = 'PAYMENT_HISTORY_FAIL';
