export const GIVE_REVIEW_AND_RATING_SAGA = 'GIVE_REVIEW_AND_RATING_SAGA';
export const GIVE_REVIEW_AND_RATING_START = 'GIVE_REVIEW_AND_RATING_START';
export const GIVE_REVIEW_AND_RATING_SUCCESS = 'GIVE_REVIEW_AND_RATING_SUCCESS';
export const GIVE_REVIEW_AND_RATING_FAIL = 'GIVE_REVIEW_AND_RATING_FAIL';

export const GET_ORDER_BOUGHT_SAGA = 'GET_ORDER_BOUGHT_SAGA';
export const GET_ORDER_BOUGHT_START = 'GET_ORDER_BOUGHT_START';
export const GET_ORDER_BOUGHT_SUCCESS = 'GET_ORDER_BOUGHT_SUCCESS';
export const GET_ORDER_BOUGHT_FAIL = 'GET_ORDER_BOUGHT_FAIL';

export const GET_ORDER_SOLD_SAGA = 'GET_ORDER_SOLD_SAGA';
export const GET_ORDER_SOLD_START = 'GET_ORDER_SOLD_START';
export const GET_ORDER_SOLD_SUCCESS = 'GET_ORDER_SOLD_SUCCESS';
export const GET_ORDER_SOLD_FAIL = 'GET_ORDER_SOLD_FAIL';

export const GET_ORDER_DETAIL_SAGA = 'GET_ORDER_DETAIL_SAGA';
export const GET_ORDER_DETAIL_START = 'GET_ORDER_DETAIL_START';
export const GET_ORDER_DETAIL_SUCCESS = 'GET_ORDER_DETAIL_SUCCESS';
export const GET_ORDER_DETAIL_FAIL = 'GET_ORDER_DETAIL_FAIL';

export const POST_TRACKING_DETAILS_SAGA = 'POST_TRACKING_DETAILS_SAGA';
export const POST_TRACKING_DETAILS_START = 'POST_TRACKING_DETAILS_START';
export const POST_TRACKING_DETAILS_SUCCESS = 'POST_TRACKING_DETAILS_SUCCESS';
export const POST_TRACKING_DETAILS_FAIL = 'POST_TRACKING_DETAILS_FAIL';

export const RESET_ORDERS = 'RESET_ORDERS';
