export const GET_DASHBOARD_COLLECTION_START = 'GET_DASHBOARD_COLLECTION_START';
export const GET_DASHBOARD_COLLECTION_SAGA = 'GET_DASHBOARD_COLLECTION_SAGA';
export const GET_DASHBOARD_COLLECTION_SUCCESS = 'GET_DASHBOARD_COLLECTION_SUCCESS';
export const GET_DASHBOARD_COLLECTION_FAIL = 'GET_DASHBOARD_COLLECTION_FAIL';

export const SET_RESULT_SEARCH_TEXT = 'SET_RESULT_SEARCH_TEXT';

export const GET_WISHLIST_START = 'GET_WISHLIST_START';
export const GET_WISHLIST_SAGA = 'GET_WISHLIST_SAGA';
export const GET_WISHLIST_SUCCESS = 'GET_WISHLIST_SUCCESS';
export const GET_WISHLIST_FAIL = 'GET_WISHLIST_FAIL';

export const ADD_WISHLIST_START = 'ADD_WISHLIST_START';
export const ADD_WISHLIST_SAGA = 'ADD_WISHLIST_SAGA';
export const ADD_WISHLIST_SUCCESS = 'ADD_WISHLIST_SUCCESS';
export const ADD_WISHLIST_FAIL = 'ADD_WISHLIST_FAIL';

export const RESET_WISHLIST = 'RESET_WISHLIST';

export const DELETE_WISHLIST_START = 'DELETE_WISHLIST_START';
export const DELETE_WISHLIST_SAGA = 'DELETE_WISHLIST_SAGA';
export const DELETE_WISHLIST_SUCCESS = 'DELETE_WISHLIST_SUCCESS';
export const DELETE_WISHLIST_FAIL = 'DELETE_WISHLIST_FAIL';

export const ADD_COIN_START = 'ADD_COIN_START';
export const ADD_COIN_SAGA = 'ADD_COIN_SAGA';
export const ADD_COIN_SUCCESS = 'ADD_COIN_SUCCESS';
export const ADD_COIN_FAIL = 'ADD_COIN_FAIL';

export const SELL_COIN_START = 'SELL_COIN_START';
export const SELL_COIN_SAGA = 'SELL_COIN_SAGA';
export const SELL_COIN_SUCCESS = 'SELL_COIN_SUCCESS';
export const SELL_COIN_FAIL = 'SELL_COIN_FAIL';

export const GET_COIN_DETAILS_START = 'GET_COIN_DETAILS_START';
export const GET_COIN_DETAILS_SAGA = 'GET_COIN_DETAILS_SAGA';
export const GET_COIN_DETAILS_SUCCESS = 'GET_COIN_DETAILS_SUCCESS';
export const GET_COIN_DETAILS_FAIL = 'GET_COIN_DETAILS_FAIL';

export const RESET_COIN_DETAILS = 'RESET_COIN_DETAILS';

export const GET_PORTFOLIO_START = 'GET_PORTFOLIO_START';
export const GET_PORTFOLIO_SAGA = 'GET_PORTFOLIO_SAGA';
export const GET_PORTFOLIO_SUCCESS = 'GET_PORTFOLIO_SUCCESS';
export const GET_PORTFOLIO_FAIL = 'GET_PORTFOLIO_FAIL';

export const RESET_PORTFOLIO = 'RESET_PORTFOLIO';

export const GET_AUCTION_PARTICIPATED_LIST_START = 'GET_AUCTION_PARTICIPATED_LIST_START';
export const GET_AUCTION_PARTICIPATED_LIST_SAGA = 'GET_AUCTION_PARTICIPATED_LIST_SAGA';
export const GET_AUCTION_PARTICIPATED_LIST_SUCCESS = 'GET_AUCTION_PARTICIPATED_LIST_SUCCESS';
export const GET_AUCTION_PARTICIPATED_LIST_FAIL = 'GET_AUCTION_PARTICIPATED_LIST_FAIL';

export const GET_AUCTION_CREATED_LIST_START = 'GET_AUCTION_CREATED_LIST_START';
export const GET_AUCTION_CREATED_LIST_SAGA = 'GET_AUCTION_CREATED_LIST_SAGA';
export const GET_AUCTION_CREATED_LIST_SUCCESS = 'GET_AUCTION_CREATED_LIST_SUCCESS';
export const GET_AUCTION_CREATED_LIST_FAIL = 'GET_AUCTION_CREATED_LIST_FAIL';

export const ADD_AUCTION_START = 'ADD_AUCTION_START';
export const ADD_AUCTION_SAGA = 'ADD_AUCTION_SAGA';
export const ADD_AUCTION_SUCCESS = 'ADD_AUCTION_SUCCESS';
export const ADD_AUCTION_FAIL = 'ADD_AUCTION_FAIL';

export const AWARD_AUCTION_START = 'AWARD_AUCTION_START';
export const AWARD_AUCTION_SAGA = 'AWARD_AUCTION_SAGA';
export const AWARD_AUCTION_SUCCESS = 'AWARD_AUCTION_SUCCESS';
export const AWARD_AUCTION_FAIL = 'AWARD_AUCTION_FAIL';

export const ADD_BID_START = 'ADD_BID_START';
export const ADD_BID_SAGA = 'ADD_BID_SAGA';
export const ADD_BID_SUCCESS = 'ADD_BID_SUCCESS';
export const ADD_BID_FAIL = 'ADD_BID_FAIL';

export const GET_BID_START = 'GET_BID_START';
export const GET_BID_SAGA = 'GET_BID_SAGA';
export const GET_BID_SUCCESS = 'GET_BID_SUCCESS';
export const GET_BID_FAIL = 'GET_BID_FAIL';

export const RESET_COLLECTION = 'RESET_COLLECTION';

export const ADD_COIN_CLASSIFY_START = 'ADD_COIN_CLASSIFY_START';
export const ADD_COIN_CLASSIFY_SAGA = 'ADD_COIN_CLASSIFY_SAGA';
export const ADD_COIN_CLASSIFY_SUCCESS = 'ADD_COIN_CLASSIFY_SUCCESS';
export const ADD_COIN_CLASSIFY_FAIL = 'ADD_COIN_CLASSIFY_FAIL';

export const DELETE_COLLECTION_START = 'DELETE_COLLECTION_START';
export const DELETE_COLLECTION_SAGA = 'DELETE_COLLECTION_SAGA';
export const DELETE_COLLECTION_SUCCESS = 'DELETE_COLLECTION_SUCCESS';
export const DELETE_COLLECTION_FAIL = 'DELETE_COLLECTION_FAIL';

export const COIN_GRADE_START = 'COIN_GRADE_START';
export const COIN_GRADE_SAGA = 'COIN_GRADE_SAGA';
export const COIN_GRADE_SUCCESS = 'COIN_GRADE_SUCCESS';
export const COIN_GRADE_FAIL = 'COIN_GRADE_FAIL';

export const BANK_NOTE_GRADE_START = 'BANK_NOTE_GRADE_START';
export const BANK_NOTE_GRADE_SAGA = 'BANK_NOTE_GRADE_SAGA';
export const BANK_NOTE_GRADE_SUCCESS = 'BANK_NOTE_GRADE_SUCCESS';
export const BANK_NOTE_GRADE_FAIL = 'BANK_NOTE_GRADE_FAIL';

export const GRADE_LIST_START = 'GRADE_LIST_START';
export const GRADE_LIST_SAGA = 'GRADE_LIST_SAGA';
export const GRADE_LIST_SUCCESS = 'GRADE_LIST_SUCCESS';
export const GRADE_LIST_FAIL = 'GRADE_LIST_FAIL';

export const GET_GRADE_REPORT_START = 'GET_GRADE_REPORT_START';
export const GET_GRADE_REPORT_SAGA = 'GET_GRADE_REPORT_SAGA';
export const GET_GRADE_REPORT_SUCCESS = 'GET_GRADE_REPORT_SUCCESS';
export const GET_GRADE_REPORT_FAIL = 'GET_GRADE_REPORT_FAIL';

export const CLASSIFY_BANK_NOTE_START = 'CLASSIFY_BANK_NOTE_START';
export const CLASSIFY_BANK_NOTE_SAGA = 'CLASSIFY_BANK_NOTE_SAGA';
export const CLASSIFY_BANK_NOTE_SUCCESS = 'CLASSIFY_BANK_NOTE_SUCCESS';
export const CLASSIFY_BANK_NOTE_FAIL = 'CLASSIFY_BANK_NOTE_FAIL';

export const CREATE_BANK_NOTE_START = 'CREATE_BANK_NOTE_START';
export const CREATE_BANK_NOTE_SAGA = 'CREATE_BANK_NOTE_SAGA';
export const CREATE_BANK_NOTE_SUCCESS = 'CREATE_BANK_NOTE_SUCCESS';
export const CREATE_BANK_NOTE_FAIL = 'CREATE_BANK_NOTE_FAIL';

export const SELL_BANK_NOTE_START = 'SELL_BANK_NOTE_START';
export const SELL_BANK_NOTE_SAGA = 'SELL_BANK_NOTE_SAGA';
export const SELL_BANK_NOTE_SUCCESS = 'SELL_BANK_NOTE_SUCCESS';
export const SELL_BANK_NOTE_FAIL = 'SELL_BANK_NOTE_FAIL';
