export const GET_ADDRESS_START = 'GET_ADDRESS_START';
export const GET_ADDRESS_SAGA = 'GET_ADDRESS_SAGA';
export const GET_ADDRESS_SUCCESS = 'GET_ADDRESS_SUCCESS';
export const GET_ADDRESS_FAIL = 'GET_ADDRESS_FAIL';

export const ADD_ADDRESS_START = 'ADD_ADDRESS_START';
export const ADD_ADDRESS_SAGA = 'ADD_ADDRESS_SAGA';
export const ADD_ADDRESS_SUCCESS = 'ADD_ADDRESS_SUCCESS';
export const ADD_ADDRESS_FAIL = 'ADD_ADDRESS_FAIL';

export const EDIT_ADDRESS_START = 'EDIT_ADDRESS_START';
export const EDIT_ADDRESS_SAGA = 'EDIT_ADDRESS_SAGA';
export const EDIT_ADDRESS_SUCCESS = 'EDIT_ADDRESS_SUCCESS';
export const EDIT_ADDRESS_FAIL = 'EDIT_ADDRESS_FAIL';

export const DELETE_ADDRESS_START = 'DELETE_ADDRESS_START';
export const DELETE_ADDRESS_SAGA = 'DELETE_ADDRESS_SAGA';
export const DELETE_ADDRESS_SUCCESS = 'DELETE_ADDRESS_SUCCESS';
export const DELETE_ADDRESS_FAIL = 'DELETE_ADDRESS_FAIL';

export const GET_COUNTRY_START = 'GET_COUNTRY_START';
export const GET_COUNTRY_SAGA = 'GET_COUNTRY_SAGA';
export const GET_COUNTRY_SUCCESS = 'GET_COUNTRY_SUCCESS';
export const GET_COUNTRY_FAIL = 'GET_COUNTRY_FAIL';

export const SET_PRIMARY_ADDRESS_START = 'SET_PRIMARY_ADDRESS_START';
export const SET_PRIMARY_ADDRESS_SAGA = 'SET_PRIMARY_ADDRESS_SAGA';
export const SET_PRIMARY_ADDRESS_SUCCESS = 'SET_PRIMARY_ADDRESS_SUCCESS';
export const SET_PRIMARY_ADDRESS_FAIL = 'SET_PRIMARY_ADDRESS_FAIL';

export const GET_NOTIFICATION_START = 'GET_NOTIFICATION_START';
export const GET_NOTIFICATION_SAGA = 'GET_NOTIFICATION_SAGA';
export const GET_NOTIFICATION_SUCCESS = 'GET_NOTIFICATION_SUCCESS';
export const GET_NOTIFICATION_FAIL = 'GET_NOTIFICATION_FAIL';

export const GET_CMS_START = 'GET_CMS_START';
export const GET_CMS_SAGA = 'GET_CMS_SAGA';
export const GET_CMS_SUCCESS = 'GET_CMS_SUCCESS';
export const GET_CMS_FAIL = 'GET_CMS_FAIL';

export const RESET_CMS = 'RESET_CMS';
