export const RESET_APP = 'RESET_APP';

export const LOGIN_SAGA = 'LOGIN_SAGA';
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const SOCIAL_NOT_REGISTERED = 'SOCIAL_NOT_REGISTERED';
export const RESET_SOCIAL_NOT_REGISTERED = 'RESET_SOCIAL_NOT_REGISTERED';

export const SIGNUP_SAGA = 'SIGNUP_SAGA';
export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const LOGOUT_SAGA = 'LOGOUT_SAGA';
export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

export const AUTHENTICATION_VALIDATOR = 'AUTHENTICATION_VALIDATOR';
export const RESET_ERROR_MSG = 'RESET_ERROR_MSG';
export const RESET_TEMP_DATA = 'RESET_TEMP_DATA';

export const OTP_VERIFY_SAGA = 'OTP_VERIFY_SAGA';
export const OTP_VERIFY_START = 'OTP_VERIFY_START';
export const OTP_VERIFY_SUCCESS = 'OTP_VERIFY_SUCCESS';
export const OTP_VERIFY_FAIL = 'OTP_VERIFY_FAIL';

export const OTP_RESEND_SAGA = 'OTP_RESEND_SAGA';
export const OTP_RESEND_START = 'OTP_RESEND_START';
export const OTP_RESEND_SUCCESS = 'OTP_RESEND_SUCCESS';
export const OTP_RESEND_FAIL = 'OTP_RESEND_FAIL';

export const FORGOT_PASSWORD_SAGA = 'FORGOT_PASSWORD_SAGA';
export const FORGOT_PASSWORD_START = 'FORGOT_PASSWORD_START';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';

export const CREATE_PASSWORD_SAGA = 'CREATE_PASSWORD_SAGA';
export const CREATE_PASSWORD_START = 'CREATE_PASSWORD_START';
export const CREATE_PASSWORD_SUCCESS = 'CREATE_PASSWORD_SUCCESS';
export const CREATE_PASSWORD_FAIL = 'CREATE_PASSWORD_FAIL';

export const GET_USER_DETAIL_SAGA = 'GET_USER_DETAIL_SAGA';
export const GET_USER_DETAIL_START = 'GET_USER_DETAIL_START';
export const GET_USER_DETAIL_SUCCESS = 'GET_USER_DETAIL_SUCCESS';
export const GET_CURRENT_USER_DETAIL_SUCCESS = 'GET_CURRENT_USER_DETAIL_SUCCESS';
export const GET_USER_DETAIL_FAIL = 'GET_USER_DETAIL_FAIL';
export const GET_CURRENT_USER_DETAIL_FAIL = 'GET_CURRENT_USER_DETAIL_FAIL';

export const EDIT_USER_DETAIL_SAGA = 'EDIT_USER_DETAIL_SAGA';
export const EDIT_USER_DETAIL_START = 'EDIT_USER_DETAIL_START';
export const EDIT_USER_DETAIL_SUCCESS = 'EDIT_USER_DETAIL_SUCCESS';
export const EDIT_USER_DETAIL_FAIL = 'EDIT_USER_DETAIL_FAIL';

export const UPDATE_PROFILE_PIC_SAGA = 'UPDATE_PROFILE_PIC_SAGA';
export const UPDATE_PROFILE_PIC_START = 'UPDATE_PROFILE_PIC_START';
export const UPDATE_PROFILE_PIC_SUCCESS = 'UPDATE_PROFILE_PIC_SUCCESS';
export const UPDATE_PROFILE_PIC_FAIL = 'EDIT_USER_DETAIL_FAIL';

export const CHANGE_PASSWORD_SAGA = 'CHANGE_PASSWORD_SAGA';
export const CHANGE_PASSWORD_START = 'CHANGE_PASSWORD_START';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';

export const BUY_VIP_MEMBERSHIP_START = 'BUY_VIP_MEMBERSHIP_START';
export const BUY_VIP_MEMBERSHIP_SAGA = 'BUY_VIP_MEMBERSHIP_SAGA';
export const BUY_VIP_MEMBERSHIP_SUCCESS = 'BUY_VIP_MEMBERSHIP_SUCCESS';
export const BUY_VIP_MEMBERSHIP_FAIL = 'BUY_VIP_MEMBERSHIP_FAIL';

export const POST_QUERY_SAGA = 'POST_QUERY_SAGA';
export const POST_QUERY_START = 'POST_QUERY_START';
export const POST_QUERY_SUCCESS = 'POST_QUERY_SUCCESS';
export const POST_QUERY_FAIL = 'POST_QUERY_FAIL';

export const UPLOAD_KYC_SAGA = 'UPLOAD_KYC_SAGA';
export const UPLOAD_KYC_START = 'UPLOAD_KYC_START';
export const UPLOAD_KYC_SUCCESS = 'UPLOAD_KYC_SUCCESS';
export const UPLOAD_KYC_FAIL = 'UPLOAD_KYC_FAIL';
