export const GET_CONVERSATION_START = 'GET_CONVERSATIONS_START';
export const GET_CONVERSATION_SAGA = 'GET_CONVERSATION_SAGA';
export const GET_CONVERSATION_SUCCESS = 'GET_CONVERSATIONS_SUCCESS';
export const GET_CONVERSATION_FAIL = 'GET_CONVERSATIONS_FAIL';

export const GET_CONVERSATION_MESSAGE_START = 'GET_CONVERSATION_MESSAGE_START';
export const GET_CONVERSATION_MESSAGE_SAGA = 'GET_CONVERSATION_MESSAGE_SAGA';
export const GET_CONVERSATION_MESSAGE_SUCCESS = 'GET_CONVERSATION_MESSAGE_SUCCESS';
export const GET_CONVERSATION_MESSAGE_FAIL = 'GET_CONVERSATION_MESSAGE_FAIL';

export const CREATE_CONVERSATION_START = 'CREATE_CONVERSATION_START';
export const CREATE_CONVERSATION_SAGA = 'CREATE_CONVERSATION_SAGA';
export const CREATE_CONVERSATION_SUCCESS = 'CREATE_CONVERSATION_SUCCESS';
export const CREATE_CONVERSATION_FAIL = 'CREATE_CONVERSATION_FAIL';

export const CREATE_CONVERSATION_MESSAGE_START = 'CREATE_CONVERSATION_MESSAGE_START';
export const CREATE_CONVERSATION_MESSAGE_SAGA = 'CREATE_CONVERSATION_MESSAGE_SAGA';
export const CREATE_CONVERSATION_MESSAGE_SUCCESS = 'CREATE_CONVERSATION_MESSAGE_SUCCESS';
export const CREATE_CONVERSATION_MESSAGE_FAIL = 'CREATE_CONVERSATION_MESSAGE_FAIL';

export const ADD_CONVERSATION_MESSAGE_SAGA = 'ADD_CONVERSATOIN_MESSAGE_SAGA';

export const CREATE_NOTIFICATION_SAGA = 'CREATE_NOTIFICATION_SAGA';
